### ISSUE TITLE
Not exactly an issue, more just a funny story

### ISSUE THREAD

**Issue by That1M8Head** [christianpatrick/hitgub#6]
There was me, just working on my not-search engine, thinking, "Hm, I should probably put a funny search query for a link" so I decided to reverse `github` into `hitgub`, just for the lols.

Then I added links to real search websites on my not-search engine and got curious... clicked it, and it brought me to a DuckDuckGo page with this repo as the first result.

Oh, and the actual program? I haven't yet tried it, but it looks like it'd be really useful!

**Comment by christianpatrick** [comment]
Ha @That1M8Head! Thanks for the story! I hope you do find it useful if you have a need to use it!
